### ISSUE TITLE
modifying a host fails because cannot delete IPv6 entry

### ISSUE THREAD

**Issue by tpdownes** [theforeman/smart_proxy_dns_infoblox#9]
I'm trying to add a host parameter but cannot because it gets part way through deletion/recreation of DNS/DHCP entries, fails and then has to revert them back.

I believe the proxy debug log below is telling me that it can't delete an IPv6 entry for my host. Although I never created one. The Foreman's 1.12 release notes indicate a lot of IPv6 DNS support was recently added.

Oddly enough, it is not an issue if I delete the host entirely. I have built the gem from 071c0b67.

```
D, [2016-08-08T14:58:06.856436 #65477] DEBUG -- : Rack::Handler::WEBrick is invoked.
D, [2016-08-08T14:58:06.857318 #65477] DEBUG -- : verifying remote client 172.20.0.10 against trusted_hosts ["deploy.nemo.uwm.edu"]
I, [2016-08-08T14:58:09.985415 #65477]  INFO -- : 172.20.0.10 - - [08/Aug/2016 14:58:09] "DELETE /dns/33.0.20.172.in-addr.arpa HTTP/1.1" 200 - 3.1282

D, [2016-08-08T14:58:09.986742 #65477] DEBUG -- : close: 172.20.0.10:54311
D, [2016-08-08T14:58:10.025809 #65477] DEBUG -- : accept: 172.20.0.10:54314
D, [2016-08-08T14:58:10.028765 #65477] DEBUG -- : Rack::Handler::WEBrick is invoked.
D, [2016-08-08T14:58:10.029615 #65477] DEBUG -- : verifying remote client 172.20.0.10 against trusted_hosts ["deploy.nemo.uwm.edu"]
E, [2016-08-08T14:58:13.034664 #65477] ERROR -- : undefined method `ipv6addr=' for nil:NilClass
D, [2016-08-08T14:58:13.034842 #65477] DEBUG -- : undefined method `ipv6addr=' for nil:NilClass (NoMethodError)
/var/lib/gems/2.1.0/gems/smart_proxy_dns_infoblox-0.0.3/lib/smart_proxy_dns_infoblox/dns_infoblox_main.rb:49:in `remove_ptr_record'
/usr/share/foreman-proxy/modules/dns/dns_api.rb:61:in `block in <class:Api>'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1603:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1603:in `block in compile!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:966:in `[]'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:966:in `block (3 levels) in route!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:985:in `route_eval'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:966:in `block (2 levels) in route!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1006:in `block in process_route'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1004:in `catch'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1004:in `process_route'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:964:in `block in route!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:963:in `each'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:963:in `route!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1076:in `block in dispatch!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `block in invoke'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `catch'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `invoke'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1073:in `dispatch!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:898:in `block in call!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `block in invoke'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `catch'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `invoke'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:898:in `call!'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:886:in `call'
/usr/lib/ruby/vendor_ruby/rack/commonlogger.rb:33:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:217:in `call'
/usr/share/foreman-proxy/lib/proxy/log.rb:63:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/xss_header.rb:18:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/path_traversal.rb:16:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/json_csrf.rb:18:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:50:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/base.rb:50:in `call'
/usr/lib/ruby/vendor_ruby/rack/protection/frame_options.rb:31:in `call'
/usr/lib/ruby/vendor_ruby/rack/nulllogger.rb:9:in `call'
/usr/lib/ruby/vendor_ruby/rack/head.rb:11:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/show_exceptions.rb:21:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:180:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:2014:in `call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1478:in `block in call'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1788:in `synchronize'
/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1478:in `call'
/usr/lib/ruby/vendor_ruby/rack/builder.rb:138:in `call'
/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:65:in `block in call'
/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
/usr/lib/ruby/vendor_ruby/rack/builder.rb:138:in `call'
/usr/lib/ruby/vendor_ruby/rack/handler/webrick.rb:60:in `service'
/usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
I, [2016-08-08T14:58:13.035599 #65477]  INFO -- : 172.20.0.10 - - [08/Aug/2016 14:58:13] "DELETE /dns/33.0.20.172.in-addr.arpa HTTP/1.1" 400 45 3.0061
```

**Comment by tpdownes** [comment]
My DHCP settings, stripped of sensitive info. The DNS settings appear to only be sensitive.

```
:record_type: fixed_address
:range: false
:infoblox_subnets: true
:wapi_version: '2.0'
:restart_sleep: 5
:restart: true
```

**Comment by tpdownes** [comment]
This diff eliminates the symptom. I can spell ruby but am otherwise unequipped to evaluate whether this is a wise choice. In various places on github, I see some back and forth between the infoblox gem and other users of this gem so hopefully it will get resolved in a way that makes sense.

```
-      ptr_record.ipv6addr=nil
+      # ptr_record.ipv6addr=nil
```
